version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -n 6 --flake8 --pep8

      - store_artifacts:
          path: test-reports
          destination: test-reports

  push-to-staging:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build --tag slack-app-staging .

      - run:
          name: Login to aws
          command: |
            sudo pip install -U awscli
            eval $(aws ecr get-login --no-include-email --region us-east-1)

      - run:
          name: Push to ECR
          command: |
            repo_url=037670161673.dkr.ecr.us-east-1.amazonaws.com
            docker tag slack-app-staging:latest $repo_url/slack-app-staging:latest
            docker push $repo_url/slack-app-staging:latest

workflows:
  version: 2
  build-test-and-push-to-staging:
    jobs:
      - build

      - hold-for-staging:
          type: approval
          requires:
            - build

      - push-to-staging:
          requires:
            - hold-for-staging
